server:
  port: 8082

spring:
  application:
    name: CityForum

  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: "HTML"
    encoding: "UTF-8"

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/city_forum?characterEncoding=utf-8&useSSL=false
    username: root
    password: gg12138.

logging:
  level:
    cn.edu.zjou: INFO

mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      id-type: ASSIGN_ID
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler


pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql


jython:
  path: "F:/jython2.7.2/" # 需要更改